config/routes.rb
Rails.application.routes.draw do
  root to: "lots#index"
  devise_for :users
  resources :users
  resources :lots
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :lot
end

app/models/lot.rb
class Lot < ActiveRecord::Base
  has_many :comments
  has_many :users, through: :comments

  has_attached_file :photo1,
    :storage => :s3,
    :url => ":s3_domain_url",
    :path => "/:class/:attachment/:id_partition/:style/:filename",
    :s3_credentials => Proc.new{|a| a.instance.s3_credentials },
    :styles => {
      :medium => "300x300>",
      :thumb => "100x100>"
    },
      :default_url => "http://placeimg.com/500/500/arch"
  validates_attachment_content_type :photo1, :content_type => /\Aimage\/.*\Z/

  validates :address, :borough, presence: true

  def s3_credentials
    {:bucket => ENV['BUCKET'], :access_key_id => ENV['AWS_ACCESS_KEY_ID'], :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']}
  end

  # def self.get_zipcode(latitude, longitude)
  #   Geocoder.search("#{latitude},#{longitude}").first.data['address_components'].last['long_name']
  # end

  # def self.get_address(latitude, longitude)
  #   Geocoder.search("#{latitude},#{longitude}").first.data['formatted_address']
  # end

  def self.get_coordinates(address)
    Geocoder.coordinates(address)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
  has_many :lots, through: :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
  def index
    @lots = Lot.all
    respond_to do |format|
      format.html
      format.json { render :json => @lots }
    end
  end

  def show
    @lot = Lot.find params[:id]
  end

  def edit

  end

  def new
    @lot = Lot.new
  end

  def create
   @lot = Lot.new
   coordinates = Lot.get_coordinates(params["lot"]["address"])
   if @lot.save
      @lot.update(
        address: params["lot"]["address"],
        borough: params["lot"]["borough"],
        zipcode: params["lot"]["zipcode"],
        agency_owner: params["lot"]["agency_owner"],
        area_sq_feet: params["lot"]["area_sq_feet"],
        area_acres: params["lot"]["area_acres"],
        latitude: coordinates[0],
        longitude: coordinates[1],
        description: params["lot"]["description"]
      )
    end
    redirect_to root_path
  end

  def destroy

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DerelictDominion</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="page">
   <header class="site-header">
      <div class="row">
         <div class="grid-full">
            <h1><%= link_to 'Derelict Dominion', root_path %></h1>
            <div class="devise-shit">
               <% if current_user %>
               <p><%=current_user.email%></p>
                 <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'logout-button'  %>
                 <%else%>
                 <%= link_to "Login", new_user_session_path, :class => 'btn btn-secondary login-button' %>
                 <%end%>
            </div>
         </div>
      </div>
   </header>
   <%= yield %>
</div>

</body>
</html>

app/views/lots/index.html.erb
<head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map-canvas { height: 100% }
    </style>
<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=#{API_KEY}">
</script>
</head>

<body>

  <section class="map">
    <div id="map-canvas"></div>
  </section>

  <section class="content">
    <div class="row">
      <div class="grid-full">

        <%= link_to "Report dereliction", new_lot_path, class: "btn btn-primary" %>

        <div class="derelict-housing">
          <% @lots.each do |lot| %>
            <ul id="derelict-housing-list" class="derelict-housing-list">
              <li class="hideme"><%= link_to lot.address, lot %></li>
              <% if lot.borough != nil %>
              <li class="hideme"><%= lot.borough %></li>
              <% end %>
            </ul>
          <% end %>
        </div>

      </div>
      <!-- /.grid-full -->
    </div>
    <!-- /.row -->
  </section>

</body>

app/views/lots/new.html.erb
<section class="content">
    <div class="row">
        <div class="grid-full">
            <%= form_for :lot, url: lots_path, :html => { :multipart => true } do |f| %>
                <div class="report-building-form">
                  <%= f.file_field :photo1 %>

                    <%= f.label :address %>
                    <%= f.text_field :address %>
                    <%= f.label :borough %>
                    <%= f.text_field :borough %>
                    <%= f.label :zipcode %>
                    <%= f.text_field :zipcode %>
                    <%= f.label :agency_owner %>
                    <%= f.text_field :agency_owner %>
                    <%= f.label :area_sq_feet %>
                    <%= f.text_field :area_sq_feet %>
                    <%= f.label :area_acres %>
                    <%= f.text_field :area_acres %>
                    <%= f.label :description %>
                    <%= f.text_field :description %>
                    <%= f.hidden_field :latitude, id: 'hidden_lat' %>
                    <%= f.hidden_field :longitude, id: 'hidden_long' %>
                    <br/>
                    <%= f.submit 'Report lot or building', class: 'btn btn-primary' %>
                </div>
            <% end %>
        </div>
    </div>
</section>

app/views/lots/show.html.erb
<section class="content">
   <div class="row">
      <div class="grid-full">
         <p><%= @lot.address %> | <%= @lot.borough %></p>
         <div><img src="<%= @lot.photo1 %>"></div>

         <% if @lot.description != nil %>
           <div><%= @lot.description %></div>
         <% end %>
      </div>
   </div>
</section>